# PostgreSQL. Versions 9.1 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DEEPFLAVOR_DATABASE_USER_DESENV'] %>
  password: <%= ENV['DEEPFLAVOR_DATABASE_PASSWORD_DESENV'] %>

development:
  <<: *default
  database: DeepFlavor_development

test:
  <<: *default
  database: DeepFlavor_test

production:
  <<: *default
  database: DeepFlavor_production
  username: <%= ENV['DEEPFLAVOR_DATABASE_USER_PROD'] %>
  password: <%= ENV['DEEPFLAVOR_DATABASE_PASSWORD_PROD'] %>
